# Generated by Django 3.2 on 2024-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image_url', models.TextField(blank=True, null=True, verbose_name='url изображения')),
                ('price', models.IntegerField(default=0.0, verbose_name='Цена')),
                ('discount', models.TextField(blank=True, default=None, null=True, verbose_name='Скидка в %')),
                ('recording_time', models.CharField(max_length=100, verbose_name='Время окончания')),
            ],
        ),
    ]
