# Generated by Django 3.2 on 2024-04-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default=1, max_length=150, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
