# Generated by Django 3.2 on 2024-04-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_parser', '0002_auto_20240421_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.TextField(max_length=150, verbose_name='Ссылка'),
        ),
    ]
